### ISSUE TITLE
Is it possible to specify a cache when using mplayer?

### ISSUE THREAD

**Issue by lee2sman** [coderholic/pyradio#103]
I tried loading a particular station's stream and found I couldn't get it to play, just getting a 'failed to connect' error. I use pyradio with mplayer on the backend.  I tested running directly from mplayer and got the error ```Cannot seek backward in linear streams!```. Ok so next I tried running directly with mplayer and adding a cache. And that works!

As an example, this works directly in Terminal:

```
mplayer https://stream-mixtape-geo.ntslive.net/mixtape -cache 1024 -
```

Is there any way I can specify a cache for mplayer like this or for this particular stream, inside pyradio?

**Comment by lee2sman** [comment]
Hi, I don't understand why this is, but I solved the error by changing url to ```http``` instead of ```https```. Now it works. Guessing some kind of stream detection doesn't happen correctly with https?

**Comment by lee2sman** [comment]
Maybe there should be a fallback for this?

**Comment by s-n-g** [comment]
Hi there @lee2sman 

Actually there is a workaround included in https://github.com/coderholic/pyradio/commit/048d104ff76ecaa25121021f6b45e3c71cbda0a4 

What version are you using?
Can you verify you are using the latest (0.8.7.2)?

BTW, I am currently busy with a project at work, that's why I'm not active, but I will be back as soon as it is over

**Comment by lee2sman** [comment]
Hi, you are correct, I was not up to date! I installed 0.8.7.2 and now https works! Thanks!
