### ISSUE TITLE
No audio output with -u vlc 

### ISSUE THREAD

**Issue by Strykar** [coderholic/pyradio#152]
Since it defaults to VLC, I had to install mplayer and now there is an audio signal.
How many I help troubleshoot this?

`pyradio-git 0.8.9.16.r0.g6d4b8db` on Arch x64.

**Comment by s-n-g** [comment]
Hi @Strykar 

I currently do not have an arch available to check this one, but I will as soon as I get back home

In the menatime, just execute

```
rm ~/pyradio.log
pyradio -d -u vlc
```
After playback has started, try to adjust the volume (press `-` or `,` to decrease, `+` or `.` to increase) and see if you get any sound and any messages

Then exit **pyradio** and post the file created: **~/pyradio.log**

**Comment by Strykar** [comment]
Pulseaudio Volume Control app shows no audio signal coming, log - https://gist.github.com/Strykar/bbede9002f11b2028cfbfda1eb82df68

**Comment by s-n-g** [comment]
Hi again @Strykar 

I have just installed vlc on `arch` and it works ok. Furthermore, I have seen your log, and it seems that **pyradio** works as expected (it shows that vlc's volume has been maxed out; gone from 90-512). 

What does that mean?
I believe this is not a **pyradio** problem, it's a **vlc** problem. 
**pyradio** has no code to produce sound; it just passes a URL to the player

Does vlc makes any sound when you play any media on it?
Maybe you just have to select the appropriate output in `pavucontrol` (or vlc settings)

**Comment by Strykar** [comment]
There is some weirdness here I cannot replicate unfortunately. Just tried opening the URL pyradio attempts from the log in VLC, and it starts playing, but the volume is maxed and muted. Unmuting it fixes the problem in VLC and pyradio.

**Comment by s-n-g** [comment]
Hi again @Strykar 

I knew vlc remembers its volume setting and restores it next time it's executed, but I could not imagine it would also remember its mute state :confused: 

So, the "weirdness" you got there is because of vlc; you probably muted it and then closed it. So, next time you used it (with pyradio or stand alone) it started muted...

pyradio does not use the mute command (no mute command exists, it seems), it just sets the volume (so mute means mute = 0). I think I have to have a better look at it

Anyway, glad you figured it out!
