### ISSUE TITLE
Adding Stations from Radio Browser to the stations list

### ISSUE THREAD

**Issue by Knusper** [coderholic/pyradio#168]
Is there a way to add a station from the radio browser to the stations list?  I read all the documentation and either I am not a good student or this is a feature that was indeed not implemented?

**Comment by s-n-g** [comment]
hi @Knusper 

:)

Here's how you do it... While in RadioBrowser select the station and press "**y**" and "**ENTER**".

Then press "**\\p**", select the playlist and press "**ENTER**".

**Comment by s-n-g** [comment]
Just an alternative to use when you want to copy more than a couple of stations...

While in RadioBrowser select the station and press "**yo**".

This will copy the station into register "**o**".

Keep adding stations in the "**o**" editor (select station, press "**yo**").

When done, open a new terminal and type:

```
cat ~/.config/pyradio/.registers/register_o.csv >> ~/.config/pyradio/stations.csv
```

That is 

cat ~/.config/pyradio/.registers/register_**o**.csv >> ~/.config/pyradio/**stations**.csv

- **o** : this is the register name you copied stations to (remember "y**o**"?) \
You can use any letter or number, instead of "**o**" as a register name when copying.
- **stations**: this is **PyRadio** default station (as you already know) 

Then return to **PyRadio**, go to your stations list and press "**R**" to reload it.

**Comment by Knusper** [comment]
Thanks. Both very useful.
