### ISSUE TITLE
WSL2 Instance Working Pretty Much... :)

### ISSUE THREAD

**Issue by gabbymouth** [coderholic/pyradio#172]
I love this app. Normal Ubuntu installs work very well OOTB. With wsl2, I call the windows mpv.exe from my ubuntu distro. I had to create a symlink from /usr/bin and I had to hack the code to run a taskkill.exe app when I select a new station. It's not perfect but it works.  I am not making a request but just throwing it out there. Your app also works fine with the IPTV stations I like with or without video...

**Comment by s-n-g** [comment]
I'm happy to hear you like this program so that you took it upon yourself to make it work with wsl2 :smile: 

Maybe you could write a guide or something?

I do not have windows on my machine, only in vm and I think wsl2 does not run there...

BTX, I suppose you know PyRadio runs on Windows as well (no need to go through wsl2).

If you want to try it, I can help you fix the crash that occurs with the latest version; I am aware of it but did not release the fix already - never imagined anyone (other than me, that is) would like to run it on Windows :smile:

**Comment by gabbymouth** [comment]
> I'm happy to hear you like this program so that you took it upon yourself to make it work with wsl2 😄
> 
> Maybe you could write a guide or something?
> 
> I do not have windows on my machine, only in vm and I think wsl2 does not run there...
> 
> BTX, I suppose you know PyRadio runs on Windows as well (no need to go through wsl2).
> 
> If you want to try it, I can help you fix the crash that occurs with the latest version; I am aware of it but did not release the fix already - never imagined anyone (other than me, that is) would like to run it on Windows 😄

I did install the windows version using python 3.8 (3.10 did not work). It seemed to install fine and I have a start menu link but when I run it, it does nothing.  Maybe that's the "crash" you are referring to... Let me know when you want me to try it again.

Regarding a wsl2 guide, if I get the time, I will throw together, in detail, what I did into a message.

**Comment by s-n-g** [comment]
> I did install the windows version using python 3.8 (3.10 did not work). It seemed to install fine and I have a start menu link but when I run it, it does nothing. Maybe that's the "crash" you are referring to... Let me know when you want me to try it again.

Yes, that's the crash I was referring to...

So, to make it work (install the windows version if you have previously uninstalled it), open a **File Explorer** and navigate to 

**%appdata%\Python**

Then **Python3**`xx` (for you it would be **Python38**, if I understood well)

The enter folder **site-packages** and then **pyradio**


Open the file `main.py` and go to line 496

https://github.com/coderholic/pyradio/blob/0.8.9.32/pyradio/main.py#L496

Delete lines 496-499, save and exit

pyradio should be lunching ok now, using the start menu link

>
> 
> Regarding a wsl2 guide, if I get the time, I will throw together, in detail, what I did into a message.

Sure, whenever you have the time :wink:

**Comment by gabbymouth** [comment]
I was finally able to get it working with vlc after re-installing using python 3.10 and your patch. The start menu link does not work (C:\Windows\System32\cmd.exe /C pyradio) returns a pyradio does not exist message. But if I run pyradio.exe from the python 3.10 Scripts folder in a cmd window it works fine with vlc. I'll have to figure out why mpv is not working but I'm fine with using vlc. Thanks for all the help!

**Comment by s-n-g** [comment]
Great!

The start menu link failure is probably because the **python 3.10 Scripts** is not in the **PATH**.

Copying `pyradio.exe` to `c:\windows\system32\` may cause a problems; when the program is updated, you will still be running the old exe, unless you remember to copy the new one (every time).

I would recommend you add the **Scripts** folder to your **PATH**.  That would be a good practice if you intend to run any other python program on windows.

In the meantime I will try to fix the start menu link...

I think I can close  this issue now, Please open a new one in case you do write the guide for the WSL2 installation

**Comment by gabbymouth** [comment]
> The start menu link failure is probably because the **python 3.10 Scripts** is not in the **PATH**.
> 
> I would recommend you add the **Scripts** folder to your **PATH**. That would be a good practice if you intend to run any other python program on windows.
> 

Correct, the scripts folder is not in my path. Duly noted and I will take appropriate action.
