### ISSUE TITLE
Show volume.

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#218]
I see volume only when I change it. I want to see it always.

**Comment by s-n-g** [comment]
No that's not possible. Sorry

Two reasons:

1. It's not easy to get the players to report back the volume value, unless the user changes it. It may be possible for vlc (and that's a thin maybe), but I'm sure it's impossible for mpv and mplayer.
2. Making this kind of change would mean that a large part of the core of the app would have to be modified, which is not worth the gain

**Comment by amano-kenji** [comment]
Are you really s ure?

I just read `man mpv`, and I found

```
get_property_string
       Like get_property, but the resulting data will always be a string.

       Example:

          { "command": ["get_property_string", "volume"] }
          { "data": "50.000000", "error": "success" }
```

**Comment by s-n-g** [comment]
> It seems to me that `updateStatus` can fetch volume along with title.

Since you are looking at the code, it's `updateMPVStatus` you should be looking at (it's the one for mpv under python 3); `updateStatus` is for all other players except mpv on python 3, `updateWinVLCStatus` is for vlc on windows only ;)

> It seems it may only require a few lines...

If only it was that simple...

From a quick look, to have the volume always on, most of the main functions in `log.py` should be modified (and I haven't looked into it carefully, there may be more).

Then, since this would be an inconstant behavior (other players will not work this way), probably a new configuration option would have to be added, something like "Always display the volume on mpv", which would call for modification of `config.py` and 'config_window.py`, and so on ans so forth...

Always showing the volume would require modification of most of the

**Comment by amano-kenji** [comment]
I think you should probably support only mpv or something. I don't see a good reason to support multiple backends.

**Comment by s-n-g** [comment]
That might be the best way, if it was a new project...

I already know that a lot of low end machines are using **PyRadio**, mainly pi, that cannot use mpv, just mplayer...

So, that's a no go...

**Comment by amano-kenji** [comment]
I just tried to play a radio station with mplayer, but mplayer gave me this.

```
$ mplayer 'https://uk2.streamingpulse.com/ssl/vcr1'
MPlayer SVN-r38428 (Gentoo)-13 (C) 2000-2023 MPlayer Team

Playing https://uk2.streamingpulse.com/ssl/vcr1.
libavformat version 60.3.100 (external)
Cannot seek backward in linear streams!
Cannot seek backward in linear streams!
Cannot seek backward in linear streams!
...
```

**Comment by s-n-g** [comment]
Try `http`

```
mplayer 'http://uk2.streamingpulse.com/ssl/vcr1'
```

In pyradio press `z` to toggle, also in the config config

Or use `mpv` or `cvlc` :wink:

**Comment by amano-kenji** [comment]
I was bored and searched the codebase.

I found `_get_text_volume` in `radio.py`. This function seems to get player volume easily.

**Comment by amano-kenji** [comment]
Afte reading the code for a while, I'm beginning to understand why mplayer should be dropped before this is possible cleanly.
