### ISSUE TITLE
I can't enable my theme

### ISSUE THREAD

**Issue by FarParticul** [coderholic/pyradio#235]
when you start the program itself, a window appears saying that the themes are disabled and it’s not clear how to enable them, it writes about some kind of color scheme, but I don’t understand
![изображение](https://github.com/coderholic/pyradio/assets/157636018/99cd639e-fb14-4c4c-9526-41d68c773a7f)
![изображение](https://github.com/coderholic/pyradio/assets/157636018/edc2cae6-678c-4990-8e0d-f73c59df7d38)

I use Arch Linux, installed the program via chaotic-aur

**Comment by s-n-g** [comment]
I have just installed arch on vm, using `archinstall`

I have the same thing; looking into it :wink:

**Comment by FarParticul** [comment]
> I have just installed arch on vm, using `archinstall`
> 
> I have the same thing; looking into it 😉

ok, thanks for at least the answer!

**Comment by s-n-g** [comment]
You are on the linux console, right (no X)?

```
$ echo $TERM
linux
```

**Comment by s-n-g** [comment]
oh, ok, yes, color change on **python curses** does not work with **konsole** (I do not know why...)

If you want to enable themes for **PyRadio** you will have to:

1. install a vte terminal (e.g. xterm, kitty, sakura, lxterminal, roxterm, kitty, sakura, etc)
2. install `libvterm` (for some reason it is not installed by default with any of the above terminals)
3. change the terminal in the **Desktop file**; more info: [Specifying the terminal to use](https://github.com/coderholic/pyradio/blob/master/docs/index.md#specifying-the-terminal-to-use)

**Comment by s-n-g** [comment]
I've been playing with this one for a while... there's nothing missing, themes do work but not with **konsole**.

To enable themes you have to 
1. Install a vte-based terminal (xterm, if you can customize it :wink: , lxterminal, termite, kitty, sakura, roxterm, etc.)
2. Change the default terminal, following the procedure described in [Specifying the terminal to use](https://github.com/coderholic/pyradio/blob/master/docs/index.md#specifying-the-terminal-to-use)

The problem I've been having, although I did install a vte-based terminal (kitty), was due to the fact that I kept starting it from within **konsole** :(

**Comment by FarParticul** [comment]
> I've been playing with this one for a while... there's nothing missing, themes do work but not with **konsole**.
> 
> To enable them you have to
> 
>     1. Install a vte-based terminal (xterm, if you can customize it 😉 , lxterminal, or from aur: kitty, sakura, roxterm, termite, etc.)
> 
>     2. Change the default terminal (to the one you have installed) , following the procedure described in [Specifying the terminal to use](https://github.com/coderholic/pyradio/blob/master/docs/index.md#specifying-the-terminal-to-use)
> 
> 
> The problem I've been having, although I did install a vte-based terminal (kitty), was due to the fact that I kept starting it from within **konsole** :(
> 
> Hope that helps

ok, I understand, then I will study kitty and sit through it
