### ISSUE TITLE
pyradio-recordings folder keeps showing in home directory

### ISSUE THREAD

**Issue by Plyply99** [coderholic/pyradio#241]
I configured pyradio to put the recordings directory inside the .config folder but every time I start pyradio the folder again appears in my home directory.

![Screenshot from 2024-05-10 01-04-52](https://github.com/coderholic/pyradio/assets/103620143/79cfe39f-603d-47de-a2cd-4fe071702c64)

Really don't want pyradio-recordings continually showing up in my home folder.

**Comment by s-n-g** [comment]
Hm... let me have a look...

**Comment by s-n-g** [comment]
fixed in `0.9.3.6`

BTW, what theme is this you are using?
Nice!

**Comment by Plyply99** [comment]
Thank you for fixing so quick!
Theme is Dracula.

**Comment by s-n-g** [comment]
Is it posted anywhere?
The only one I find is this [dracula.pyradio-theme](https://github.com/mechatour/hyprland_dotfiles/blob/main/.config/pyradio/themes/dracula.pyradio-theme), but this one is a different theme

**Comment by Plyply99** [comment]
> Is it posted anywhere? The only one I find is this [dracula.pyradio-theme](https://github.com/mechatour/hyprland_dotfiles/blob/main/.config/pyradio/themes/dracula.pyradio-theme), but this one is a different theme

It's one I modified.

[dracula.pyradio-theme.txt](https://github.com/coderholic/pyradio/files/15279938/dracula.pyradio-theme.txt)


Just delete the .txt at the end, I put it there so I could upload it here.

**Comment by s-n-g** [comment]
I have somewhat modified your beautiful theme, hope you like it and permit me to include it in PyRadio's next release

[dracula_by_Plyply99.pyradio-theme.txt](https://github.com/coderholic/pyradio/files/15283253/dracula_by_Plyply99.pyradio-theme.txt)

**Comment by Plyply99** [comment]
Looks great and please do!

Thank you.

**Comment by s-n-g** [comment]
Wonderful!
I have it already added to devel branch
Thank you!

**Comment by lee2sman** [comment]
Sorry to comment on closed. Let me know if you want me to open new issue, or "won't fix." I am running 0.9.3.9. I read your above closed as fixing this problem in 0.9.3.6 but in the current version I'm running it still creates a directory called pyradio-recordings in the home folder. I find this frustrating.

Since I am not recording, it keeps adding an empty directory every time. Why couldn't the default be "No folder added" but if someone does record, at that point it checks and add the directory? OR...If for some reason you need to add this directory, it should not default to the home folder but instead to ~/.config/pyradio.
Thanks for considering.

**Comment by s-n-g** [comment]
Sure, no problem, let me see what I can come up with :)

**Comment by s-n-g** [comment]
On second thought, can you please open a new issue?
