### ISSUE TITLE
[Suggestion] Colour change of Menu

### ISSUE THREAD

**Issue by Catoptrix** [coderholic/pyradio#60]
Hi! I love this application, thank you.

It would be cool though, if I could change the default colours. I would prefer a violet instead of green.
Is there a way I could change that?

Cheers

**Comment by martynjy** [comment]
Yes, I agree.  
A colour change option such as in 'calcurse' would be a nice addition.

**Comment by s-n-g** [comment]
Working on it...

**Comment by v00v** [comment]
+1, I would love to be able to change default colors or even create a custom theme.

**Comment by s-n-g** [comment]
Unfortunately, I have done nothing to this issue...

But if you are willing to get your hands dirty a bit, I can tell you how to create your color scheme.

First of all you need to  be able to see the colors your terminal supports. For this purpose I use [terminal-colors](https://github.com/eikenb/terminal-colors), but any similar tool will do.

```
terminal-colors -n
```

will give me a list of colors and their corresponding number.

Ok, now you need an existing color scheme, for example [purple_by_sng.pyradio-theme](https://github.com/coderholic/pyradio/raw/master/pyradio/themes/purple_by_sng.pyradio-theme). This is its content:

```
PyRadio URL = 57,134
Messages Border = 129,134
Status Bar = 226,129
Stations = 195,134
Active Station = 56,134
Active Cursor = 226,129
Normal Cursor = 123,171
Edit Cursor = 123,171
```

There are 8 pairs of foreground, background colors defining various aspects of **PyRadio**'s TUI.

| PyRadio URL     | The color of the URL at the top right corner                                    |
|-----------------|---------------------------------------------------------------------------------|
| Messages Border | The color of the border for the messages windows (just press "?" to see it)     |
| Status Bar      | The color of the status bar (last line)                                         |
| Stations        | The color of a station (not playing, not selected)                              |
| Active Station  | The color of the station that's currently playing, when the cursor IS NOT on it |
| Active Cursor   | The color of the station that's currently playing, when the cursor IS on it     |
| Normal Cursor   | The normal cursor line color                                                    |
| Edit Cursor     | The color of the edit cursor (press "e" to see it)                              |

To test your color scheme, just save it a ```~/.config/pyradio/themes/[WHATEVER].pyradio-theme``` and press "**t**" withing **PyRadio** to activate it.

That's all.

If anyone does take the time to create a color scheme, please do post it here; I could just include it in the next release.

**Comment by v00v** [comment]
@s-n-g, Very nice. Thank you for sharing this. I will definitely try it! Just wish you supported more CSS like colors #000000 etc.

**Comment by s-n-g** [comment]
@v00v I haven't really looked into it, but I think curses does not use CSS like colors; it's more like using
```
color1 = ....
color2 = ....
```

etc, with colors coming rfom the active palette

**Comment by s-n-g** [comment]
I did have a read about colors under curses, and it seems CSS colors are actually supported (well, RGB values can be assigned to colors) but this is a totally different logic compared to the one currently implemented here.

Playing with colors was done at the very begining of my starting working on this project, and at a time I knew nothing about curses, so I missread / missunderstood the meaning of things. As a result, my whole approach is wrong :sob: 

But hey, it is what it is!
It will have to be like that until other more important things are implemented...

**Comment by edunfelt** [comment]
I ended up just applying some minor tweaks to the original theme by creating a new `.pyradio-theme`-file as above with the 0-15 values I prefer. Maybe adding this suggestion to the README under the PyRadio Themes section could point users in that direction?

Using [base16 shell](https://github.com/chriskempson/base16-shell) the default looks really good already, not sure if there would be a point in creating a base16 template repo to add more themes using CSS colors? I could try my hand at this if you'd think it's a reasonable idea.

(Awesome app btw <3)

**Comment by edunfelt** [comment]
I ended up just applying some minor tweaks to the original theme by creating a new `.pyradio-theme`-file as above with the 0-15 values I prefer. Maybe adding this suggestion to the README under the PyRadio Themes section could point users in that direction?

Using [base16 shell](https://github.com/chriskempson/base16-shell) the default looks really good already, not sure if there would be a point in creating a base16 template repo to add more themes using CSS colors? I could try my hand at this if you'd think it's a reasonable idea.

(Awesome app btw <3)

**Comment by s-n-g** [comment]
Hi @edunfelt 

> I ended up just applying some minor tweaks to the original theme by creating a new .pyradio-theme-file as above with the 0-15 values I prefer. 

Please do share!

>Maybe adding this suggestion to the README under the PyRadio Themes section could point users in that direction?

Well, I haven't done that (yet?) just because I really am not happy the way this whole theming thing is implemented... But then again, this may be the way to go (more on this later)...

> Using [base16](https://github.com/chriskempson/base16-shell) shell the default looks really good already, not sure if there would be a point in creating a base16 template repo to add more themes using CSS colors? I could try my hand at this if you'd think it's a reasonable idea.

I am afraid you've lost me here...
Do you mean: create base16 templates to be used with **PyRadio**'s "*dark*" theme? :confused: 
Can you please explain?

Either way, thank you for the offer to help out!

BTW, I have been looking into this (redefining colors in python and using **base16**) for the last couple of hours (that's why it took me so long to reply :satisfied: )

So, here's what I found out...
`python` can redefine the value of a given color (for example **color01**) provided that the terminal used provides this feature. And this is where the fun begins... I have tested a couple of terminals and most of them do provide this feature, but **xterm** does not (and probably most of the terminal based on it like aterm and eterm).

So, using the current scheme (with the limitation that the definition of colors is done by the terminal, i.e. the pallete) works everywhere. Using a CSS based color scheme, will define its colors (hopefully all terminals will display blue when the color is rgb(255, 0, 0) or #FF0000) but all xterm based terminals will crash trying to do so...

As you can see, I am in "trial and error" mode here with this... and I may stil be wrong, but anyways... this is how far I got with it... I will not look into it any more at this time, though; I am trying to finish the "Radio Browser" integration (which is long overdue...)


> (Awesome app btw <3)

Thank you very much!

**Comment by edunfelt** [comment]
Hi @s-n-g :)

> Please do share!

Currently the theme file looks like this:
```
PyRadio URL = 2,0
Messages Border = 2,0
Status Bar = 0,1
Stations = 7,0
Active Station = 1,0
Active Cursor = 0,1
Normal Cursor = 0,3
Edit Cursor = 0,8
```
with resulting appearance
![image](https://user-images.githubusercontent.com/29271899/117253569-9e7f8380-ae47-11eb-9c37-414386183743.png)
So it's slightly different than the regular main color being green. 

> Can you please explain?

Sorry if I was being unclear! The [Base16 architecture](https://github.com/chriskempson/base16) can be used to build themes for applications using a scheme template. If there is a possibility to use CSS colors I think it might be possible to create a Base16 template from which the builder can generate CSS-based themes.

I now also looked into this for a while based on what you said, and it seems like it could work possibly.  I think maybe using [`curses.init_color()`](https://docs.python.org/3.6/library/curses.html#curses.init_color) instead of `curses.init_pair()` might be a solution for supported terminals? This doesn't appear too difficult to test, I could look into it once my agenda clears up a bit (thesis project work... :sweat_smile:).

Alternatively a menu option or something of that sort to simply change the default 0-15 values could work, like was mentioned above. But this is ultimately less flexible than RGB although probably sufficient for most people.

**Comment by s-n-g** [comment]
Hi again @edunfelt 

So, you are probably using `base16_atelier-plateau-light`, right?
BTW, is that a tilling WM with inner and outer margins that I see? Cool!

Here's how mine looks using `base16_atelier-plateau-light`:

![Mabox_2021-05-06-13-15-1620296127](https://user-images.githubusercontent.com/5807638/117282525-8589c900-ae6d-11eb-9315-ca7ed8fe26e0.png)


I, on the other hand, normally use `base16_summerfruit-dark` (well, had its color in my terminal config), and here's how your theme looks like for me: :sob: 

![Mabox_2021-05-06-13-17-1620296242](https://user-images.githubusercontent.com/5807638/117282794-ceda1880-ae6d-11eb-8e7d-c8afc7bffa8f.png)

> I now also looked into this for a while based on what you said, and it seems like it could work possibly. I think maybe using [curses.init_color()](https://docs.python.org/3.6/library/curses.html#curses.init_color) instead of curses.init_pair() might be a solution for supported terminals?

Well, that depends on what you want to do...

So, here who it all works in curses:

First you have color values (palette) assigned to color numbers. 
Then the program defines color pairs (foreground, background) of color numbers (not color values).
Then you use these color pairs to display some text.

This is how my current themes work. I get a color pair (of color numbers) and display the text with whatever color value those color numbers happen to correspond to. Then, each theme changes the color numbers of the given color pairs.

In a CSS based theming scheme you could just define the color pairs once (with predefined color numbers) and then go on and change the color value of each color number used, within the theme.
This is absolutely possible and doable.

But then you have those terminals that do not allow toy to change the color values. So you just have to use (revert to) the non-CSS theming scheme to allow the user to somehow see different colors...

So, maybe a combination of both **curses.init_color** and **curses.init_pair** should be used to cover all cases. I don't know, I have to think about it...

> This doesn't appear too difficult to test, I could look into it once my agenda clears up a bit (thesis project work... sweat_smile).

This is a test script I found and "touched": https://gist.github.com/s-n-g/0f1e2fe2255917ba1b74a947958d5486

You can run it as
```
python init_8_colors.py
```

On an xterm based terminal it will just terminate after the first screen.
To see it crashing, just pass anything as a parameter

```
python init_8_colors.py crash
```




> The [Base16 architecture](https://github.com/chriskempson/base16) can be used to build themes for applications using a scheme template. If there is a possibility to use CSS colors I think it might be possible to create a Base16 template from which the builder can generate CSS-based themes.

Ok, so what you mean here is that you could try to create a Base16 template which will be used to somehow create ready-to-use CSS-based themes for PyRadio? I hope I got it right this time :smile: 

If this is the case, that would be great!

The thing I have in mind is something like:

```
PyRadio URL = #HHHHHH, #HHHHHH
Messages Border = #HHHHHH, #HHHHHH
Status Bar = #HHHHHH, #HHHHHH
Stations = #HHHHHH, #HHHHHH
Active Station = #HHHHHH, #HHHHHH
Active Cursor = #HHHHHH, #HHHHHHx
Normal Cursor = #HHHHHH, #HHHHHH
Edit Cursor = #HHHHHH, #HHHHHH
```

where **HH** the hex value for r, g, b

So, yes, you can try to create such a template, take your sweet time about it though, I will not be able to work on it before Radio Browser support is fully implemented...

What do you think?

**Comment by edunfelt** [comment]
@s-n-g 

> So, you are probably using base16_atelier-plateau-light, right?

I am using `base16_cupcake` scheme actually, it has a slightly more pinkish tone that I find very comforting for long hours at the screen. And yes I'm using Xmonad tiling WM :D

> I, on the other hand, normally use base16_summerfruit-dark (well, had its color in my terminal config), and here's how your theme looks like for me:

Summerfruit is a good one indeed :smiley: The modified theme is picking up teh default terminal scheme, switching to `base16_cupcake` will make it look identical to my system I'm guessing.

> So, maybe a combination of both curses.init_color and curses.init_pair should be used to cover all cases. I don't know, I have to think about it...

Yeah, this sounds like reasonable solution, maybe keeping the theming as it works now (or something similar) when `curses.can_change_color()` is False, and use the `curses.init_color()` if it is True. Can confirm the script works on Kitty terminal as well :)

> Ok, so what you mean here is that you could try to create a Base16 template which will be used to somehow create ready-to-use CSS-based themes for PyRadio? I hope I got it right this time smile

Yes, exactly! I think generating theme files like that with the hex values would be possible this way. I'll look into this as time allows.
If it's still open whenever you have time to look at it again, you can just @ me :smile: 

Have a nice day/evening/morning!

**Comment by s-n-g** [comment]
Closing this on too...
Done in `0.8.9.21`
