### ISSUE TITLE
Ctrl+m starts playing a station. Alt+m kills pyradio.

### ISSUE THREAD

**Issue by crocket** [coderholic/pyradio#79]
I don't think those are shortcuts used by pyradio. Is it a bug?

**Comment by s-n-g** [comment]
@crocket thanks for pointing this out; I am aware of this, it is due to the way that the keyboard input is handled internally, and because of the long and complex history of terminals and their APIs.

Actually, all Alt combinations will be considered as ESCAPE at this point.
This is what happens: Alt-M is passed to the program as an escape sequence (ESCAPE-M). Also Alt-N as ESCAPE-N and so on. This can be easily fixed.

Ctrl combinations are a different story altogether. For example, Ctrl-J will also start playing a station, Ctrl-[ will exit the program (ESCAPE), Ctrl-S will suspend execution, Ctrl-Z will return from the suspended state, etc.

I will have to look into these

**Comment by s-n-g** [comment]
Alt combinations no longer cause a problem. I don't think I can do anything about Control combinations...

Considering it closed
