### ISSUE TITLE
Browsing new stations from within pyradio

### ISSUE THREAD

**Issue by fn-ix** [coderholic/pyradio#80]
Hi!

It would be really nice if it was possible to explore new radio stations from within pyradio itself, so that one doesn't have to go hunting on the web separately for them. I could recommend radio-browser.info, which is a large community database of internet radio streams that also has an API that should make it possible to integrate it with pyradio; other apps, such as Gradio, also use it.

I hope this can be taken under consideration, although it would be a big undertaking! :)

**Comment by s-n-g** [comment]
Hi @hfel 

Thank you for your suggestion!
I was thinking of implementing something like that, maybe something opml related.
But this is for the future... So stay tuned
S.

**Comment by dimyself** [comment]
I like this idea as well...similar to how curseradio has stations implemented would be great! In fact it's the reason I still use curseradio over pyradio. It uses this URL to import stations: http://opml.radiotime.com/

Thanks!

**Comment by s-n-g** [comment]
@dimyself 
I have already started working on integrating http://www.radio-browser.info/
So, as I've told to @hfel , stay tuned...

**Comment by dimyself** [comment]
@s-n-g thanks man! I was wondering if going through radio-browser.info would have a similar interface to browse through different genres (not just tags)? For instance if I go through opml.radiotime.com in this category: http://opml.radiotime.com/Browse.ashx?c=music ... I can then drill down into a specific category to see for example the dance/electronic category: http://opml.radiotime.com/Browse.ashx?id=c57941  which will then have sub categories such as chill, dubstep, drum & bass, House, Trance, most popular (for this particular genre / sub-genre), etc... or also the ability to brose genre / sub-genre (local) stations and shows. 

I only bring all this up, because if I go to radio-browser.info, I don't see this kind of granularity? The only thing I see that kind of matches categories is "tags"? Maybe I just don't see all the categories/sections that are available on the site? 

Anyway, its worth looking into maybe just to see which might have superior browsing... If you want to get an idea of how the browsing works in terminal/ncurses, you can check out curseradio which already has this url implemented for browsing and drilling down into the opml categories. It seems to have just about everything, so much stuff! 

I apologize if I missed something in the radio-browser site that allows for better browsing down more granular, or if you have some kind of plan to categorize all the tags for example. 

Is there a way you plan for pyradio to be able to drill down using radio-browser? For instance, if I click on the 'talk' tag on radio-browser, it just shows ALL talk tag stations (which is enormous). I don't see a way to see: 'Talk' AND 'Religion' (to further drill down to only show those partiular stations. 

I think it will still be very hard to find specific sub-genre stations a person is looking for with just specific tags? ...Unless I'm missing something on the radio-browser.info site

Anyway, idk how far you've gotten using that site, but its worth looking into opml radiotime because of the way the categories / sub-categories are setup.

Thanks!

**Comment by s-n-g** [comment]
Hi @dimyself 

No, I don't think an interface such as this is exactly possible with http://www.radio-browser.info/

The closest to genre is a tag, but then again the categorization is done on station level; there is not a category provided by the server per se.

I have managed to get this though (on a terminal)...

```
curl --header "Content-Type: application/json" \
  --request POST \
--data '{"tagList":"talk,religion"}' \
http://www.radio-browser.info/webservice/json/stations/search
```

That's searching for tags **talk** and **religion**. 
If you run it through **json_reformat -su** you can get the name, tag, url etc...

```
curl --header "Content-Type: application/json" \
  --request POST \
--data '{"tagList":"talk,religion"}' \
http://www.radio-browser.info/webservice/json/stations/search | json_reformat -su | grep name
```

Doing that within pyradio is a whole different thing though.
So I'm just working on the interface right now; this is where i am right now: station by top votes...

https://imagebin.ca/v/530bQ9hXJX6R

My next objective is to create a search interface, but it takes time...

Now, regarding http://opml.radiotime.com/ , it may well be the next service to integrate

Regards,
Spiros

**Comment by amano-kenji** [comment]
pyradio already supports radiobrowser pagination. Can this issue be closed?
