### ISSUE TITLE
macOS Catalina Read-only file system error

### ISSUE THREAD

**Issue by st-f** [coderholic/pyradio#97]
Getting this error at installation:

```creating 'dist/pyradio-0.8.7.1-py3.7.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing pyradio-0.8.7.1-py3.7.egg
removing '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyradio-0.8.7.1-py3.7.egg' (and everything under it)
creating /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyradio-0.8.7.1-py3.7.egg
Extracting pyradio-0.8.7.1-py3.7.egg to /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
pyradio 0.8.7.1 is already the active version in easy-install.pth
Installing pyradio script to /Library/Frameworks/Python.framework/Versions/3.7/bin

Installed /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyradio-0.8.7.1-py3.7.egg
Processing dependencies for pyradio==0.8.7.1
Finished processing dependencies for pyradio==0.8.7.1
mv: rename pyradio.1.gz to /usr/share/man/man1/pyradio.1.gz: Read-only file system
mkdir: /usr/local/share/doc/pyradio: File exists```

**Comment by s-n-g** [comment]
Hi @st-f 

It seems this is due to MacOS Catalina, which runs in a read-only system volume
https://support.apple.com/en-us/HT210650

I have a Mojave installation on VBox (my testing suite) but I will have to get a Catalina box on VBox somehow.

Now back to your installation log:
What I understand is that a) you are upgrading ```pyradio``` and b) the manpage cannot be written to ```/usr/share/man/man1``` (due to the read-only filesystem), but it seems that the application has been installed?

Do you have ```pyradio 0.8.7.1``` installed?

**Comment by s-n-g** [comment]
Fixed in 570c6a875055739b605c6cf60297b5fc4ac21e8f
Thank you for reporting this!

**Comment by st-f** [comment]
Hi @s-n-g, thanks for the swift reply! I assumed it wasn't installed because of the warning, but it actually did work. I ended up using the latest develop as there was a git error when using a release, not sure if that actually fixed it or if the install was successful the first time

**Comment by s-n-g** [comment]
Hi again
I think it was installed the first time; it was just the manpage that did not
But now I've fixed it too, so all is well
